# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: RYM Scrape

on:
  workflow_dispatch:
    
  repository_dispatch:
    types:
      - webhook
      
  schedule:
    - cron: "0 10 * * 0-1"


jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: pnpm/action-setup@v2
        with:
          version: 7.25.0
          run_install: true
      - run: |
          node scraping/new_releases.js
          git config user.name rym-scrape-bot
          git config user.email tomas.opazoasd@gmail.com
          git add .
          git commit -m "[auto] updated db"
          git push -u origin main
